//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;
        ///	&lt;Modulus&gt;wjVr7bbkHIYUdwUdXx2jx7usS7locwMztGTKKZ9bCvWU5/lmI11eAiSB/a25CzKihT7R116G7/+I9zHCTnGhnKokqZRnsQ35StscegnN+VtJkogfpxi1VXp+OYeEsYx3OWOgj5MixT92Mokb0NmeE7oMzgH8NJfS0Vv9HinHJ9E=&lt;/Modulus&gt;
        ///	&lt;Exponent&gt;AQAB&lt;/Exponent&gt;
        ///	&lt;P&gt;4DLM4gop5d38NWYCWALU+yIJCNaNBvBlzMo0Q04STcQvzs3vSgZO55jxrojB2Z9g+ln32qcb8S5D178tvKsd4w==&lt;/P&gt;
        ///	&lt;Q&gt;3cGecMWSNC1dhDVy7YjPeFn5cR69EPvVp9PljlZ/OQpjPaDZZJVZ7h1USGDYPH6+41TZ9IiMDXS+TK0M4rbRuw==&lt;/Q&gt;
        ///	&lt;DP&gt;Tb6P+ZpYqRNvT/0NtwNUY7mLtHrh8JQQWRGNSgGaq0jq4yXaYqsJVZpdxI472oFAGdB0+GeWcu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RsaProps {
            get {
                return ResourceManager.GetString("RsaProps", resourceCulture);
            }
        }
    }
}
